### ISSUE TITLE
getting a cURL error 6: Could not resolve host: candy-store.test (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (View: /var/www/html/candy-store/resources/views/_layouts/base.blade.php) (View: /var/www/html/candy-store/resources/views/_layouts/base.blade.php)

### ISSUE THREAD

**Issue by nyck33** [getcandy/candy-api#59] opened 2018-09-02 01:58 UTC
## Expected Behavior

I want to launch the quick start store doing `php artisan serve` but instead I get an error when I click the URL.

## Current Behavior

Getting this error.

## Possible Solution

No idea.  I'm new to this.  

## Steps to Reproduce

1.  I followed the quickstart installation instruction wiki, set my .env file, etc
2.  I'm on a LAMP setup, no Homestead, no VM, 18,04 Ubuntu 
3.
4.

**Comment by nyck33** [comment] 2018-09-02 02:02
```
/var/www/html/candy-store/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php
                new RequestException(
                    'An error was encountered during the on_headers event',
                    $easy->request,
                    $easy->response,
                    $easy->onHeadersException,
                    $ctx
                )
            );
        }
 
        $message = sprintf(
            'cURL error %s: %s (%s)',
            $ctx['errno'],
            $ctx['error'],
            'see http://curl.haxx.se/libcurl/c/libcurl-errors.html'
        );
 
        // Create a connection exception if it was a specific error code.
        $error = isset($connectionErrors[$easy->errno])
            ? new ConnectException($message, $easy->request, null, $ctx)
            : new RequestException($message, $easy->request, $easy->response, null, $ctx);
 
        return \GuzzleHttp\Promise\rejection_for($error);
    }
 
    private function getDefaultConf(EasyHandle $easy)
    {
        $conf = [
            '_headers'             => $easy->request->getHeaders(),
            CURLOPT_CUSTOMREQUEST  => $easy->request->getMethod(),
            CURLOPT_URL            => (string) $easy->request->getUri()->withFragment(''),
            CURLOPT_RETURNTRANSFER => false,
            CURLOPT_HEADER         => false,
            CURLOPT_CONNECTTIMEOUT => 150,
        ];
 
        if (defined('CURLOPT_PROTOCOLS')) {
            $conf[CURLOPT_PROTOCOLS] = CURLPROTO_HTTP | CURLPROTO_HTTPS;
        }
 
Arguments
"cURL error 6: Could not resolve host: candy-store.test (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (View: /var/www/html/candy-store/resources/views/ ▶"

```

**Comment by alecritson** [comment] 2018-09-03 08:04
Looks like a dupe of #54

**Closed by alecritson** 2018-09-03 08:04 UTC
